### PR TITLE
Changelog: Reference original PR author if backport was created by grafanabot

### LINKED ISSUE #46: Update-changlog: Author detection for backports
If a PR that should be included in the changelog is also a backport, we should do some further checks to keep the author information relevant. If the author of the backport is a bot (either Grot or something else) then we should fall back to the author of the original PR.

The number of the original PR can be determined through the branch name (`backport-$NUM-to-$BASE`)

### PR DESCRIPTION
**Pull request by zerok**
Unfortunately, this requires fetching the PR explicitly through the API as there is no other relation to it and you cannot query a handful of PRs by number.

To keep the number of API requests down I've also switched the initial search request with a request to the GraphQL API as this allows fetching of all PRs that are associated with a milestone.

Fixes #46 

## How to test

You can run the following command to generate a preview of the changelog for 10.0.1:

```
INPUT_SKIP_COMMUNITY_POST=1 INPUT_SKIP_PR=1 INPUT_VERSION=10.0.1 go run ./update-changelog --preview
```

This requires a `GITHUB_TOKEN` environment variable.

### CODE REVIEW

**Review by dsotirakis — COMMENTED** [review]
I think we should use the `grafana-delivery-bot` gh app for this?

**Comment by zerok** [comment]
> I think we should use the `grafana-delivery-bot` gh app for this?

Already on it :) Just trying to figure out which formatting of that app user is the right now :D The `gh` CLI returns something ... unexpected ;)

**Comment by zerok** [comment]
> > I think we should use the `grafana-delivery-bot` gh app for this?
> 
> Already on it :) Just trying to figure out which formatting of that app user is the right now :D The `gh` CLI returns something ... unexpected ;)

```
{
  "data": {
    "repository": {
      "pullRequest": {
        "author": {
          "resourcePath": "/apps/grafana-delivery-bot",
          "login": "grafana-delivery-bot"
        }
      }
    }
  }
}
```

Resource path it is :P

**Comment by zerok** [comment]
@dsotirakis fixed :D

**Review by dsotirakis — APPROVED** [review]
Mighty, let's see how it behaves 👀

**Pull request merged**
